# This is an example for building a D application

language: d
dist: trusty
sudo: false

# Those were trial and error, is there a systematic way to know them?
addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev
      - libsdl2-mixer-dev
      - libgl1-mesa-dev 
      
before_install:
  # Use the dub-updating fork of the installer script until https://github.com/dlang/installer/pull/301 is merged
  - wget https://raw.githubusercontent.com/wilzbach/installer-dub/master/script/install.sh -O ~/dlang/install.dub.sh
  - . $(bash ~/dlang/install.dub.sh -a dub)
  - dub --version

d:
  - dmd

script:
  - dub build
  - ls
  - find starspacediamond # https://github.com/CosmicCitadel/StarSpaceDiamond/issues/1#issuecomment-485451909
  - file starspacediamond # Is this the main game executable?
  - mkdir -p appdir/usr/bin ; cp starspacediamond appdir/usr/bin/ # FIXME, make install should do that
  - cp -r resources appdir/usr/bin/ # FIXME, make install should do that
  - mkdir -p appdir/usr/share/applications ; cp starspacediamond.desktop appdir/usr/share/applications/ # FIXME, make install should do that
  - mkdir -p appdir/usr/share/icons/scalable/apps/ ; touch appdir/usr/share/icons/scalable/apps/starspacediamond.svg # FIXME
  - cp appdir/usr/share/icons/scalable/apps/starspacediamond.svg . # FIXME
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  # export VERSION=... # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  # find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq # for debugging
  # curl --upload-file APPNAME*.AppImage https://transfer.sh/APPNAME-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh StarSpaceDiamond*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
