# This is an example for building a D application

language: d
dist: trusty
sudo: false

# Those were trial and error, is there a systematic way to know them?
addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev
      - libsdl2-mixer-dev
      - libgl1-mesa-dev 
      
before_install:
  # Use the dub-updating fork of the installer script until https://github.com/dlang/installer/pull/301 is merged
  - wget https://raw.githubusercontent.com/wilzbach/installer-dub/master/script/install.sh -O ~/dlang/install.dub.sh
  - . $(bash ~/dlang/install.dub.sh -a dub)
  - dub --version

d:
  - dmd

script:
  - dub build

after_success:
  - ls
  - ls app.d # https://github.com/CosmicCitadel/StarSpaceDiamond/issues/1#issuecomment-485451909
